services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - ./ollama_data:/root/.ollama
      - ./ollama_scripts:/scripts
    entrypoint: ['/bin/bash', '/scripts/start_ollama.sh']
    tty: true
    env_file:
      - .env.shared
    restart: unless-stopped
